### ISSUE TITLE
getHeadingDegrees error

### ISSUE THREAD

**Issue by iam-black** [psiphi75/compass-hmc5883l#1]
Hello. Iam trying to use this lib with a NodeJS and Raspberri Pi 2. getRawValues works fine, but getHeadingDegrees example generates folowing error:

```
/home/pi/node_modules/compass-hmc5883l/Compass.js:190
        callback(null, self.calcHeading(axis1, axis2, vector).bind(self));
                                                              ^

TypeError: self.calcHeading(...).bind is not a function
    at /home/pi/node_modules/compass-hmc5883l/Compass.js:190:63
    at i2cCallback (/home/pi/node_modules/compass-hmc5883l/Compass.js:154:13)
```

**Comment by psiphi75** [comment]
Fixed.  Thanks for the bug report.  It's published to npm as well.  So you just need to run `npm update compass-hmc5883l`.
